apiVersion: v1
kind: Service
metadata:
  name: {{ template "dgraph.alpha.fullname" . }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.alpha.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    monitor: {{ .Values.alpha.monitorLabel }}
spec:
  type: {{ .Values.alpha.service.type }}
  loadBalancerIP: {{ .Values.alpha.service.ip }}
  ports:
  - port: 8080
    targetPort: 8080
    name: alpha-http
  - port: 9080
    targetPort: 9080
    name: alpha-grpc
  # We want all pods in the StatefulSet to have their addresses published for
  # the sake of the other Dgraph alpha pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  selector:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.alpha.name }}
    release: {{ .Release.Name }}
