apiVersion: v1
kind: Service
metadata:
  name: {{ template "dgraph.ratel.fullname" . }}
  # This annotation will help to create internal TCP load balancer for gcloud
  # Documentation: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing
  # This required type as 'LoadBalancer' and we can specify static ip with 'loadBalancerIP'
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.ratel.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ratel.service.type }}
  loadBalancerIP: {{ .Values.ratel.service.ip }}
  ports:
  - port: 8000
    targetPort: 8000
    name: ratel-http
  selector:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.ratel.name }}
    release: {{ .Release.Name }}
